######### Register #########
POST {{apiUrl}}/auth/register HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "first_name": "San",
	"last_name": "Chea",
	"phone_number": "+855162126",
	"email": "san@gmail.com",
	"password": "password",
	"password_confirmation": "password"
}


######### Login #########
POST {{apiUrl}}/auth/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "san@gmail.com",
	"password": "newpassword"
}


######### Logout #########
POST {{apiUrl}}/auth/logout HTTP/1.1
Content-Type: application/json
Accept: application/json
authorization: {{token}}


######### Logout #########
POST {{apiUrl}}/auth/reset-logged-in-password HTTP/1.1
Content-Type: application/json
Accept: application/json
authorization: {{token}}

{
	"password": "password",
	"new_password": "newpassword"
}