######### Register #########
POST {{apiUrl}}/auth/register HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "first_name": "Many",
	"last_name": "Tiv",
	"phone_number": "+85516212699",
	"email": "many@gmail.com",
	"password": "password",
	"password_confirmation": "password"
}


######### Login #########
POST {{apiUrl}}/auth/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "email": "cheasan99@gmail.com",
	"password": "password"
}


######### Logout #########
POST {{apiUrl}}/auth/logout HTTP/1.1
Content-Type: application/json
Accept: application/json
authorization: {{token}}