######### forget password #########
POST {{apiUrl}}/auth/forgot-password HTTP/1.1
Content-Type: application/json
Accept: application/json

{
   	"email": "many@gmail.com"
}


######### verify pin #########
POST {{apiUrl}}/auth/verify-pin HTTP/1.1
Content-Type: application/json
Accept: application/json

{
   	"email": "many@gmail.com",
	"token": "589471"
}


######### reset password #########
POST {{apiUrl}}/auth/reset-password HTTP/1.1
Content-Type: application/json
Accept: application/json

{
	"token": "$2y$10$eBxiL6tUDNNB2DuGCnXtyOea4j2kqYGnpqvm.FLALC2b/2CgEdx5e",
	"password": "newpassword"
}
